## *** Start Here ***

In [1]:
import sys
sys.path.append('/home/vahid/source_codes/')
import numpy as np
import pandas as pd
import pandas_ta as ta
import matplotlib.pyplot as plt
import pandas as pd
from pathlib import Path
import manual_trading as mylib
import importlib
import mlfinlab as ml
%load_ext autoreload

start_date = '2009-01-02'
end_date = '2021-01-01'
ticker = 'AAPL'

/home/vahid/source_codes/manual_trading/mypyfolio/pos.py:26: UserWarning: Module "zipline.assets" not found; multipliers will not be applied to position notionals.
  warnings.warn(

In [7]:

inpath = Path().resolve()/'data'

full_data_path = Path().resolve().parent/'data'
full_tick_df = pd.read_hdf(full_data_path/'2021-8-19_USDJPY.h5', 's')
# bars = pd.read_hdf(full_data_path/'bars'/'USDJPY_dollar_bars_monthlythr_50_bp_day.h5', 's')
# bars_ej = pd.read_hdf(full_data_path/'bars'/'EURJPY_minute_bars.h5', 's')
# bars_eu = pd.read_hdf(full_data_path/'bars'/'EURUSD_minute_bars.h5', 's')
# # s_dollar_bars = pd.read_parquet(inpath/'..'/'..'/'data'/'AAPL_dollar_bars.parquet')
# s_tick_df = pd.read_parquet(inpath/'..'/'..'/'data'/'AAPL.parquet')

# vs_dollar_bars = pd.read_parquet(inpath/'very_small_dollar_bars.parquet')
# vs_tick_df = pd.read_parquet(inpath/'very_small_AAPL.parquet')

# vvs_dollar_bars = pd.read_parquet(inpath/'vv_dollar_bars.parquet')
# vvs_tick_df = pd.read_parquet(inpath/'vv_AAPL.parquet')
bars = pd.read_hdf('/home/vahid/source_codes/data/bars/AAPL_10min_bars.h5', key='s')
bars.drop(['tick_num', 'cum_buy_volume', 'cum_ticks', 'cum_dollar_value'], axis=1, inplace=True)
n_cpus = 23

In [8]:
bars

                date_time     open    high     low     close     volume
0     2018-08-27 08:10:00  216.780  216.90  216.78  216.9000     2460.0
1     2018-08-27 08:20:00  216.900  216.90  216.86  216.9600      576.0
2     2018-08-27 08:30:00  216.960  217.08  216.96  216.8700     1162.0
3     2018-08-27 08:40:00  216.870  216.90  216.87  217.0000      202.0
4     2018-08-27 08:50:00  217.000  217.00  217.00  217.0000       22.0
...                   ...      ...     ...     ...       ...        ...
28562 2020-08-28 13:40:00  504.100  505.05  501.80  501.8600  1960304.0
28563 2020-08-28 13:50:00  501.860  503.10  500.02  500.4100  1637448.0
28564 2020-08-28 14:00:00  500.410  503.51  499.43  503.5000  1760364.0
28565 2020-08-28 14:10:00  503.500  503.52  501.61  502.4050  1146313.0
28566 2020-08-28 14:20:00  502.405  504.00  501.46  502.1399   740613.0

[28567 rows x 6 columns]

In [5]:
first_index = pd.Timestamp('2010-01-01 00:00:00.000000000', unit='ns')
bars = bars.drop(np.where(bars.date_time < first_index)[0], axis=0)

last_index = pd.Timestamp('2021-08-16 00:00:00.000000000', unit='ns')
bars = bars.drop(np.where(bars.date_time >= last_index)[0], axis=0)

In [ ]:
bars.set_index('date_time', inplace=True)
bars_ej.set_index('date_time', inplace=True)
bars_eu.set_index('date_time', inplace=True)

In [ ]:
first_index = pd.Timestamp('2010-01-01 00:00:00')
last_index = pd.Timestamp('2021-08-15 23:59:00')
bars_ej = bars_ej.loc[first_index:last_index]
bars_eu = bars_eu.loc[first_index:last_index]

In [ ]:
pd.options.display.max_rows = 4000
pd.options.display.max_seq_items = 2000

In [ ]:
# Assign small or large dataframes to the dataframes used for the whole notebook
# tick_df = full_tick_df
# tick_df.reset_index(drop=True, inplace=True)
# tick_df = tick_df[['date_time', 'price', 'volume']]

# bars = full_dollar_bars
# bars.reset_index(drop=True, inplace=True)

# del full_tick_df, full_dollar_bars

In [ ]:
bars.rename(columns={'tick_num':'end_index'}, inplace=True)
bars['start_index'] = bars['end_index'].shift(1)
bars['start_index'].iloc[0] = 0
bars['start_index'] = bars['start_index'].astype(int)

/home/vahid/miniconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [ ]:
# last_index = pd.Timestamp('2010-01-01 00:00:00.000000000', unit='ns')
# bars = bars.drop(np.where(bars.date_time < last_index)[0], axis=0)
# bars.set_index('date_time', inplace=True)

# tick_df = tick_df.drop(np.where(tick_df.index < bars.iloc[0].start_index)[0], axis=0)
# tick_df = tick_df.drop(np.where(tick_df.index > bars.iloc[-1].end_index)[0], axis=0)
# tick_df = tick_df[['date_time', 'price', 'volume']]
# tick_df.tail()

In [ ]:
# TODO
# develope a cumsumfilter that keeps 5 bars before the major move
# develop a formula for the min_return
# modify vertical barriers and get_events target parameter  equal daily volatily rolling sum
# import mlfinlab as ml
# daily_vol = ml.util.get_daily_vol(close=bars.set_index('date_time')['close'], lookback=50)
# daily_vol[daily_vol < 0].head(1000)

In [ ]:
bars_path = Path().resolve().parent/'data'/'bars'

bars = pd.read_hdf(bars_path/'AAPL_10min_bars.h5', 's')

In [ ]:
bars = bars.set_index('date_time')

In [ ]:
bars

,tick_num,open,high,low,close,volume,cum_buy_volume,cum_ticks,cum_dollar_value
date_time,,,,,,,,,
2018-08-27 08:10:00,25,216.780,216.90,216.78,216.9000,2460.0,1629.0,24,5.335005e+05
2018-08-27 08:20:00,30,216.900,216.90,216.86,216.9600,576.0,500.0,5,1.249314e+05
2018-08-27 08:30:00,40,216.960,217.08,216.96,216.8700,1162.0,1158.0,10,2.521938e+05
2018-08-27 08:40:00,46,216.870,216.90,216.87,217.0000,202.0,2.0,6,4.380788e+04
2018-08-27 08:50:00,47,217.000,217.00,217.00,217.0000,22.0,22.0,1,4.774000e+03
...,...,...,...,...,...,...,...,...,...
2020-08-28 13:40:00,74063134,504.100,505.05,501.80,501.8600,1960304.0,885767.0,36115,9.867110e+08
2020-08-28 13:50:00,74093188,501.860,503.10,500.02,500.4100,1637448.0,744024.0,30054,8.214047e+08
2020-08-28 14:00:00,74123789,500.410,503.51,499.43,503.5000,1760364.0,867370.0,30601,8.824536e+08
2020-08-28 14:10:00,74143162,503.500,503.52,501.61,502.4050,1146313.0,523383.0,19373,5.764265e+08
2020-08-28 14:20:00,74157043,502.405,504.00,501.46,502.1399,740613.0,336272.0,13881,3.719049e+08


## Labeling

In [ ]:
%autoreload 2
pt_sl = [1., 1.]
avg_events_per_day = 10
num_days_avg_vol = 90
min_ret = 0.008
n_cpus = 2
triple_barrier_events = mylib.labeling.create_triple_barrier_events_datetime(
                                         bars=bars,
                                         n_jobs=n_cpus,
                                         avg_events_per_day=avg_events_per_day,
                                         num_days_avg_vol=num_days_avg_vol,
                                         min_ret= min_ret,
                                         max_trade_length=1,
                                         pt_sl=pt_sl,
                                         side_prediction=None)

labels = ml.labeling.get_bins(triple_barrier_events, bars['close'])
print("Label value counts:")
print(labels.bin.value_counts())
print('labels count: ', labels.shape[0])

Volatility averaged for the last 90 days
1/10 of average daily volatility used as filter_threshold for the cumsum filter
Filter threshold is: 0.0012056812126029525

2021-10-10 23:05:18.340904 100.0% apply_pt_sl_on_t1 done after 0.1 minutes. Remaining 0.0 minutes..

Label value counts:
 1    2197
-1    2095
 0    1982
Name: bin, dtype: int64
labels count:  6274

In [ ]:
new_bars = pd.DataFrame(range(bars.shape[0]), index=bars.index, columns=['idx'])
# new_bars['idx'] = range(bars.shape[0])
indexes = new_bars.loc[labels.index,'idx'].to_list()
indexes = indexes + [x-1 for x in indexes] + [x-2 for x in indexes]+ [x-3 for x in indexes]+ [x-4 for x in indexes]+ [x-5 for x in indexes]
indexes = pd.Series(list(set(indexes)))
indexes = indexes[indexes >= 0].values

print(len(indexes))
del new_bars

110380

In [ ]:
# bars = bars.loc[labels.index, :]
bars = bars.iloc[indexes, :]
bars

,end_index,open,high,low,close,volume,cum_buy_volume,cum_ticks,cum_dollar_value,start_index
date_time,,,,,,,,,,
2010-01-05 02:08:50.457999872,103164447,92.2925,92.3325,92.2425,92.2750,9253.0,3891.0,1474,853854.1675,103162973
2010-01-05 02:43:44.416000000,103165455,92.2775,92.2850,92.1875,92.1950,9256.0,3751.0,1008,853843.6650,103164447
2010-01-05 03:16:42.292000000,103166558,92.1950,92.2650,92.1950,92.1950,9264.0,4185.0,1103,854384.1400,103165455
2010-01-05 04:00:03.011000064,103167686,92.1975,92.2025,92.1275,92.1525,9273.0,4521.0,1128,854629.9775,103166558
2010-01-05 04:28:44.324000000,103168956,92.1525,92.1850,91.9875,92.0100,9272.0,4020.0,1270,853960.0450,103167686
...,...,...,...,...,...,...,...,...,...,...
2021-08-13 11:20:16.961999872,328804801,110.2660,110.2850,110.2335,110.2450,1685.0,793.0,986,185791.5935,328803815
2021-08-13 11:45:30.089999872,328805780,110.2455,110.2620,110.2025,110.2385,1684.0,703.0,979,185621.5860,328804801
2021-08-13 12:18:50.352999936,328806709,110.2390,110.2510,110.1830,110.2265,1684.0,749.0,929,185609.4150,328805780
2021-08-13 12:39:55.129999872,328807546,110.2270,110.2440,110.1905,110.2075,1684.0,737.0,837,185609.8190,328806709
2021-08-13 13:04:45.211000064,328808482,110.2080,110.2265,110.1820,110.1855,1684.0,778.0,936,185583.0575,328807546

## Fractional Differentiation

In [ ]:
def df_aggregate(df, bars):
    new_df = pd.DataFrame(index=bars.index, columns=['open', 'high', 'low', 'close', 'volume'])
    prev_index = None
    i = 0
    for row in bars.itertuples():
        if prev_index is None:
            prev_index = row.Index
            new_df['open'].iloc[i] = np.nan
            new_df['high'].iloc[i] = np.nan
            new_df['low'].iloc[i] = np.nan
            new_df['close'].iloc[i] = np.nan
            new_df['volume'].iloc[i] = np.nan
            i += 1
            continue
        start_index = prev_index
        if i == 1:
            start_iloc = df.index.get_loc(start_index, method='pad')
        else:
            start_iloc = df.index.get_loc(start_index, method='pad') + 1
        end_iloc = df.index.get_loc(row.Index, method='pad')

        if start_iloc == end_iloc:
            new_df.loc[row.Index, 'open'] = df['open'].iloc[start_iloc]
            new_df.loc[row.Index, 'high'] = df['high'].iloc[start_iloc]
            new_df.loc[row.Index, 'low'] = df['low'].iloc[start_iloc]
            new_df.loc[row.Index, 'close'] = df['close'].iloc[end_iloc]
            new_df.loc[row.Index, 'volume'] = df['volume'].iloc[start_iloc]
        else:
            new_df.loc[row.Index, 'open'] = df['open'].iloc[start_iloc]
            new_df.loc[row.Index, 'high'] = df['high'].iloc[start_iloc:end_iloc].max()
            new_df.loc[row.Index, 'low'] = df['low'].iloc[start_iloc:end_iloc].min()
            new_df.loc[row.Index, 'close'] = df['close'].iloc[end_iloc]
            new_df.loc[row.Index, 'volume'] = df['volume'].iloc[start_iloc:end_iloc].sum()
        prev_index = row.Index
        i += 1
    return new_df

In [ ]:
bars_ej = df_aggregate(bars_ej, bars)
bars_eu = df_aggregate(bars_eu, bars)

for col in bars_ej.columns:
    bars_ej[col] = bars_ej[col].astype(np.float64)
    bars_eu[col] = bars_eu[col].astype(np.float64)

In [ ]:
print(bars_ej.head())
print(bars_ej.tail())

                                   open      high       low     close  volume
date_time
2010-01-05 02:08:50.457999872       NaN       NaN       NaN       NaN     NaN
2010-01-05 02:43:44.416000000  133.0250  133.0325  132.8875  132.8675  6580.0
2010-01-05 03:16:42.292000000  132.8675  133.0100  132.8375  132.9575  6566.0
2010-01-05 04:00:03.011000064  132.9575  132.9925  132.8625  132.9175  7954.0
2010-01-05 04:28:44.324000000  132.9175  132.9700  132.7625  132.8100  6301.0
                                   open      high       low     close  volume
date_time
2021-08-13 11:20:16.961999872  129.5460  129.6040  129.5270  129.5835  2483.0
2021-08-13 11:45:30.089999872  129.5825  129.6450  129.5795  129.6540  2510.0
2021-08-13 12:18:50.352999936  129.6555  129.6745  129.6165  129.6500  3036.0
2021-08-13 12:39:55.129999872  129.6510  129.6710  129.6280  129.6780  1755.0
2021-08-13 13:04:45.211000064  129.6775  129.6985  129.6290  129.6430  2308.0

In [ ]:
bars = bars.reset_index().drop(0, axis=0).reset_index(drop=True)
bars_eu = bars_eu.reset_index().drop(0, axis=0).reset_index(drop=True)
bars_ej = bars_ej.reset_index().drop(0, axis=0).reset_index(drop=True)

In [ ]:
ej_bars_path = Path().resolve().parent/'data'/'bars'/'EURJPY_minute_bars_aggregated_3.h5'
bars_ej = pd.read_hdf(ej_bars_path, 's')

eu_bars_path = Path().resolve().parent/'data'/'bars'/'EURUSD_minute_bars_aggregated_3.h5'
bars_eu = pd.read_hdf(eu_bars_path, 's')

In [ ]:
# ej_bars_path = Path().resolve().parent/'data'/'bars'/'EURJPY_minute_bars_aggregated_2.h5'
# bars_ej.to_hdf(ej_bars_path, mode='w', key='s', data_columns=True)

# eu_bars_path = Path().resolve().parent/'data'/'bars'/'EURUSD_minute_bars_aggregated_2.h5'
# bars_eu.to_hdf(eu_bars_path, mode='w', key='s', data_columns=True)

In [ ]:
%%time
%autoreload 2

min_d, new_bars = mylib.ml_utils.calc_fractional_diff(bars, thresh=1e-4)
min_d_ej, new_bars_ej = mylib.ml_utils.calc_fractional_diff(bars_ej, thresh=1e-3)
min_d_eu, new_bars_eu = mylib.ml_utils.calc_fractional_diff(bars_eu, thresh=1e-3)
min_d

Differentiating: 100%|██████████| 4/4 [00:01<00:00,  2.29it/s]
Differentiating: 100%|██████████| 4/4 [00:00<00:00,  5.41it/s]
Differentiating: 100%|██████████| 4/4 [00:01<00:00,  3.94it/s]

CPU times: user 11 s, sys: 16.2 s, total: 27.2 s
Wall time: 3.64 s

0.3

In [ ]:
bars_eu = new_bars_eu.dropna()
bars = new_bars.loc[bars_eu.index]
bars_ej = new_bars_ej.loc[bars_eu.index]

bars = bars.reset_index(drop=True)
bars_ej = bars_ej.reset_index(drop=True)
bars_eu = bars_eu.reset_index(drop=True)

In [ ]:
min_d

0.3

## TS features

In [ ]:
# %%time
# %autoreload 2

# from tsfresh.feature_extraction import (MinimalFCParameters,
#                                         EfficientFCParameters,
#                                         ComprehensiveFCParameters)
# ts_features = mylib.feature_generation.create_ts_features(bars=bars,
#                                                           periods=periods,
#                                                           n_jobs=n_cpus,
#                                                           parameters=ComprehensiveFCParameters)
# ts_features.tail()

## TA features

In [ ]:
# bars = bars.set_index('date_time')
# bars_ej = bars_ej.set_index('date_time')
# bars_eu = bars_eu.set_index('date_time')

In [ ]:
%autoreload 2
lags = [5, 10, 20, 60]

# bars = bars.set_index('date_time')
ta_features = mylib.feature_generation.create_ta_features(bars, n_jobs=20, verbose=True, lags=lags)
ta_features_ej = mylib.feature_generation.create_ta_features(bars_ej, n_jobs=20, verbose=True, lags=lags)
ta_features_eu = mylib.feature_generation.create_ta_features(bars_eu, n_jobs=20, verbose=True, lags=lags)
# ta_features.tail(10)

Numbers of indicators added to multiprocessing jobs: 124

2021-09-06 03:50:31.468621 100.0%  done after 0.84 minutes. Remaining 0.0 minutes.

Creating log_return, percent_return, entropy, and autocorrelation features...
Done.
Numbers of indicators added to multiprocessing jobs: 124

2021-09-06 03:51:30.599550 100.0%  done after 0.89 minutes. Remaining 0.0 minutes.

Creating log_return, percent_return, entropy, and autocorrelation features...
Done.
Numbers of indicators added to multiprocessing jobs: 124

2021-09-06 03:52:29.172734 100.0%  done after 0.88 minutes. Remaining 0.0 minutes.

Creating log_return, percent_return, entropy, and autocorrelation features...
Done.

In [27]:
%autoreload 2
importlib.reload(mylib)
my_ta = mylib.feature_generation.add_my_features(bars)
# my_ta_ej = add_my_features(bars_ej)
# my_ta_eu = add_my_febatures(bars_eu)
my_ta.index = bars['date_time']

In [22]:
my_ta.isna().sum().sort_values(ascending=False)

sf2_time        199
sf_time         199
vy_time         155
usk_time         49
lf_time          49
u_time           49
k_time           49
upk_time         49
sk_time          49
p_time           49
lfk_time         49
concave_time     15
a_time           14
v_time           13
vs_time          13
0                13
edpo_close       11
vvol_time         1
dtype: int64

In [28]:
my_ta.tail(120)

,a_time,v_time,vy_time,vs_time,vvol_time,concave_time,u_time,k_time,upk_time,usk_time,p_time,lfk_time,lf_time,edpo_close,sk_time,sf_time,sf2_time,0
date_time,,,,,,,,,,,,,,,,,,
2020-08-25 13:10:00,0.313416,52.283178,-0.307692,52.292741,214.328463,1.0,-0.142312,1.796462,1.654149,-1.938774,23.738297,0.007427,-0.388304,-1.294085,0.000284,-0.000125,-0.000125,2.103571
2020-08-25 13:20:00,0.219256,53.379459,-0.410000,53.388825,87.209740,-1.0,-0.141370,2.564211,2.422840,-2.705581,34.413255,0.005475,-0.292238,-1.047029,0.000282,-0.000071,-0.000071,2.154286
2020-08-25 13:30:00,-0.407822,51.340350,2.433333,51.350088,113.809950,-1.0,0.405397,3.913532,4.318930,-3.508135,51.015182,-0.013244,0.679957,-0.262550,-0.000810,0.000312,0.000312,2.060000
2020-08-25 13:40:00,0.747418,55.077438,-1.522807,55.086516,3227.970996,1.0,-9.513350,50.995003,41.481652,-60.508353,700.637607,0.271744,-14.966939,-0.150879,0.019001,-0.039395,-0.039395,2.238571
2020-08-25 13:50:00,0.627353,58.214205,-0.703557,58.222794,-49.578692,-1.0,-5.128272,33.210755,28.082483,-38.339027,475.707716,0.130467,-7.595033,2.823490,0.010250,-0.016005,-0.016005,2.417143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-08-28 13:40:00,1.737312,26.638520,-0.290179,26.657284,4553.058701,1.0,-16.269142,30.719844,14.450702,-46.988987,249.311967,3.069396,-81.764170,-0.132190,0.032315,-0.030763,-0.030763,1.367357
2020-08-28 13:50:00,1.508487,34.180954,-0.424828,34.195579,-32.939381,-1.0,-10.227262,23.941058,13.713796,-34.168319,231.711490,1.116651,-38.168186,-0.854362,0.020332,-0.025247,-0.025247,1.523071
2020-08-28 14:00:00,1.899845,43.680182,0.264078,43.691627,15.013118,1.0,-12.121532,24.066180,11.944648,-36.187711,278.327897,0.883244,-38.580266,0.115577,0.024067,-0.074699,-0.074699,1.755214
2020-08-28 14:10:00,0.578991,46.575138,-0.348858,46.585872,-69.764094,-1.0,-2.233151,14.800727,12.567575,-17.033878,179.467297,0.118644,-5.525881,0.046475,0.004436,-0.000089,-0.000089,1.868071
2020-08-28 14:20:00,0.701972,50.084996,-1.916258,50.094978,-70.783460,1.0,-1.668642,9.295133,7.626491,-10.963775,118.952435,0.068733,-3.442469,0.598725,0.003315,-0.005290,-0.005290,1.995929

In [ ]:
bars = bars.dropna()

In [ ]:
# ta_features = ta_features.drop(ta_features.columns[ta_features.isna().sum() > 200], axis=1).fillna(method='ffill')
# ta_features_ej = ta_features_ej.drop(ta_features_ej.columns[ta_features_ej.isna().sum() > 200], axis=1).fillna(method='ffill')
# ta_features_eu = ta_features_eu.drop(ta_features_eu.columns[ta_features_eu.isna().sum() > 200], axis=1).fillna(method='ffill')
my_ta = my_ta.drop(my_ta.columns[my_ta.isna().sum() > 1200], axis=1).fillna(method='ffill')

In [ ]:
ta_features = ta_features.loc[:, ~ta_features.columns.duplicated()]
ta_features_ej = ta_features_ej.loc[:, ~ta_features_ej.columns.duplicated()]
ta_features_eu = ta_features_eu.loc[:, ~ta_features_eu.columns.duplicated()]

In [ ]:
import pandas_ta as ta
tas = []
periods = [5, 14, 25, 60]
bars.set_index('date_time', inplace=True)
for period in periods:
    tas.append(ta.trend.adx(high=np.log(bars.high), low=np.log(bars.low), close=np.log(bars.close), mamode='ema', length=period))
    tas.append(ta.trend.aroon(high=np.log(bars.high), low=np.log(bars.low), length=period))
    tas.append(ta.trend.dpo(close=np.log(bars.close), length=period))

    tas.append(ta.momentum.kst(close=np.log(bars.close), signal=period))
    tas.append(ta.momentum.macd(close=np.log(bars.close), fast=14, slow=52, length=period))
    tas.append(ta.momentum.macd(close=np.log(bars.close), fast=14, slow=120, length=period))
    tas.append(ta.momentum.macd(close=np.log(bars.close), fast=14, slow=252, length=period)) 
    tas.append(ta.momentum.macd(close=np.log(bars.close), fast=25, slow=52, length=period))
    tas.append(ta.momentum.macd(close=np.log(bars.close), fast=25, slow=120, length=period))
    tas.append(ta.momentum.macd(close=np.log(bars.close), fast=25, slow=252, length=period))   

    for p2 in periods:
        if p2 > period:
            tas.append(ta.momentum.trix(close=np.log(bars.close), length=period, signal=p2))
        else:
            continue
    tas.append(ta.overlap.vwap(high=np.log(bars.high), low=np.log(bars.low), close=np.log(bars.close), volume=bars.volume, offset=period))

tas = pd.concat(tas, axis=1)
tas.reset_index(inplace=True)
# bars.reset_index(inplace=True)
ta_features = pd.concat([ta_features, tas], axis=1)
ta_features = ta_features.loc[:, ~ta_features.columns.duplicated()]
ta_features.reset_index(drop=True, inplace=True)
ta_features.tail(10)

,ACCBL_20,ACCBM_20,ACCBU_20,ADOSC_3_10,AD,AO_5_34,AMATe_LR_2,AMATe_SR_2,APO_12_26,BOP,...,TRIX_25_60,TRIXs_25_60,ADX_60,DMP_60,DMN_60,AROOND_60,AROONU_60,AROONOSC_60,DPO_60,KSTs_60
86235,15.012399,15.036612,15.068906,10850.500423,-1.947476e+08,-0.088117,0,1,-0.100404,0.209837,...,0.000864,0.010393,4.831648,49.693208,47.573666,83.333333,30.000000,-53.333333,NaN,194.514686
86236,15.001482,15.023197,15.056176,7438.262589,-1.947499e+08,-0.086419,0,1,-0.088618,-4.924041,...,0.000104,0.010255,4.756849,48.932439,48.597228,81.666667,28.333333,-53.333333,NaN,181.258108
86237,14.988770,15.012604,15.043698,15936.804242,-1.947167e+08,-0.090249,0,1,-0.070922,20.611754,...,-0.000562,0.010106,4.703423,49.362532,47.854408,80.000000,26.666667,-53.333333,NaN,168.313611
86238,14.978381,15.004069,15.036718,19478.445314,-1.947120e+08,-0.085634,1,0,-0.061551,11.075802,...,-0.001125,0.009947,4.680976,50.929056,47.621085,78.333333,25.000000,-53.333333,NaN,156.167454
86239,14.967787,14.995524,15.028448,33275.347097,-1.946676e+08,-0.085892,1,0,-0.056839,2.209531,...,-0.001595,0.009779,4.648150,50.564368,47.894770,76.666667,23.333333,-53.333333,NaN,144.964802
86240,14.962891,14.987622,15.016720,37525.207595,-1.946625e+08,-0.080056,1,0,-0.046485,2.249177,...,-0.002050,0.009602,4.613088,49.771423,47.301443,75.000000,21.666667,-53.333333,NaN,134.663546
86241,14.954417,14.979905,15.008953,36656.053306,-1.946599e+08,-0.068274,0,1,-0.038381,-0.217566,...,-0.002479,0.009417,4.554799,49.629066,48.533812,73.333333,20.000000,-53.333333,NaN,125.304938
86242,14.936479,14.969228,15.009433,32326.577143,-1.946620e+08,-0.069223,0,1,-0.034379,-1.053946,...,-0.002998,0.009221,4.513579,47.787177,49.818923,71.666667,18.333333,-53.333333,NaN,116.046766
86243,14.930560,14.959739,14.994113,25489.386385,-1.946686e+08,-0.095610,0,1,-0.030444,-2.024394,...,-0.003561,0.009013,4.485816,47.299548,50.072496,70.000000,16.666667,-53.333333,NaN,106.613597
86244,14.955716,14.959436,14.961339,20948.433580,-1.946668e+08,-0.108761,0,1,-0.027907,-0.019826,...,-0.004136,0.008792,4.424714,48.877118,49.685059,68.333333,15.000000,-53.333333,NaN,97.274266

In [ ]:
ta_features['date_time'] = bars.index
# ta_features = ta_features.fillna(method='ffill').dropna()

In [ ]:
# ta_file_path = Path().resolve().parent/'data'/'features_data'/'USDJPY_dollar_50bpd_ta_df.h5'
# ta_features.to_hdf(ta_file_path, mode='w', key='s', data_columns=True)

# ta_ej_file_path = Path().resolve().parent/'data'/'features_data'/'EURJPY_dollar_50bpd_ta_df.h5'
# ta_features_ej.to_hdf(ta_ej_file_path, mode='w', key='s', data_columns=True)

# ta_eu_file_path = Path().resolve().parent/'data'/'features_data'/'EURUSD_dollar_50bpd_ta_df.h5'
# ta_features_eu.to_hdf(ta_eu_file_path, mode='w', key='s', data_columns=True)

my_ta_file_path = Path().resolve().parent/'data'/'features_data'/'USDJPY_dollar_50bpd_my_ta.h5'
my_ta.to_hdf(my_ta_file_path, mode='w', key='s', data_columns=True)
# ts_features.reset_index(drop=True, inplace=True)
# ta_features.reset_index(drop=True, inplace=True)
# bars.reset_index(inplace=True)

In [ ]:
my_ta.isna().sum()

a_tick                    328
a_time                    324
a_volume                  324
v_tick                    323
v_time                    323
v_volume                  323
slopes_tick               323
slopes_time               323
slopes_volume             323
slope_changes_tick        328
slope_changes_time        324
slope_changes_volume      324
concave_tick                0
concave_time                0
concave_volume              0
u_tick                    525
u_time                    521
u_volume                  521
k_tick                    323
k_time                    323
k_volume                  323
upk_tick                  530
upk_time                  521
upk_volume                521
usk_tick                  528
usk_time                  521
usk_volume                521
p_tick                    323
p_time                    323
p_volume                  323
lfk_tick                 1128
lfk_time                  522
lfk_volume                522
lf_tick                  1128
lf_time                   522
lf_volume                 522
edpo_close              86245
sk_tick                   525
sk_time                   521
sk_volume                 521
sf_tick                   525
sf_time                   521
sf_volume                 521
gapatr_0                  335
rvol_tick                 323
rvol_time                 323
rvol_volume               323
downtotal_0               341
trangeatr_0               335
topsbuttoms_0               0
dtype: int64

In [ ]:
ss = pd.DataFrame(get_v(bars.reset_index())['tick'].head(1000))

## My Features

In [ ]:
s1 = pd.DataFrame(get_a(bars))
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
s1 = sc.fit_transform(s1)
s1 = pd.DataFrame(s1, columns=['tick', 'time', 'volume'])
s1

/tmp/ipykernel_7161/4057672312.py:11: RuntimeWarning: invalid value encountered in log
  accs.update({base:np.log(dv/d_base)})

           tick      time    volume
0           NaN       NaN       NaN
1           NaN       NaN       NaN
2           NaN -0.059962       NaN
3      0.575804       NaN       NaN
4      0.118977       NaN -1.018531
...         ...       ...       ...
85918       NaN       NaN       NaN
85919 -2.321839       NaN       NaN
85920       NaN       NaN       NaN
85921 -0.354999  0.922440  0.317164
85922  1.337704       NaN       NaN

[85923 rows x 3 columns]

In [ ]:
my_ta = add_my_features(bars.reset_index())
my_ta

/home/vahid/miniconda3/lib/python3.8/site-packages/pandas/core/arraylike.py:364: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/home/vahid/miniconda3/lib/python3.8/site-packages/pandas/core/arraylike.py:364: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/tmp/ipykernel_7161/233051950.py:220: RuntimeWarning: invalid value encountered in true_divide
  np.multiply(data, (alpha * scaling_factors[-2]) / scaling_factors[:-1],
/tmp/ipykernel_7161/233051950.py:225: RuntimeWarning: invalid value encountered in true_divide
  out /= scaling_factors[-2::-1]

,a_tick,a_time,a_volume,v_tick,v_time,v_volume,vy_tick,vy_time,vy_volume,vs_tick,...,sf_volume,sf2_tick,sf2_time,sf2_volume,gapatr_0,rvol_tick,rvol_time,rvol_volume,trangeatr_0,topsbuttoms_0
0,NaN,NaN,NaN,NaN,NaN,NaN,-6.436973,NaN,-1.615565,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,NaN,NaN,NaN,-4.440191,-0.027829,0.167832,NaN,NaN,NaN,0.000070,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2,-0.000152,0.010068,-0.000229,-4.604132,0.073151,0.165740,NaN,NaN,NaN,0.000050,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
3,0.000076,-0.006589,-0.000720,-4.528703,0.002719,0.159154,NaN,NaN,NaN,0.000058,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
4,0.000041,-0.019437,0.000466,-4.489513,-0.271922,0.163410,NaN,NaN,NaN,0.000063,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85918,-0.000003,-0.011400,-0.000227,-4.701149,-0.309790,0.497100,NaN,NaN,NaN,0.000041,...,-0.000336,-0.000005,-0.016877,-0.000336,-0.013982,36066.144794,156.612090,403.254411,0.028175,-1.0
85919,0.000001,-0.011585,-0.000065,-4.698976,-0.586662,0.496576,-8.316924,-4.204611,-3.121373,0.000041,...,0.000271,-0.000006,0.048427,0.000271,-0.051515,36029.646825,561.603853,402.368745,-0.003105,1.0
85920,-0.000208,-0.007828,-0.001272,-5.188534,-3.254143,0.486281,NaN,NaN,NaN,0.000016,...,0.000965,0.000157,0.005938,0.000965,-3.066146,43928.155388,17279.333901,385.858349,-0.023755,-1.0
85921,0.000021,0.045255,0.000810,-5.139970,-1.221291,0.492838,NaN,NaN,NaN,0.000017,...,-0.001914,-0.000051,-0.106880,-0.001914,0.961188,43108.742732,2433.786576,396.325691,-0.010855,0.0
85922,0.000214,-0.007562,-0.000286,-4.797768,-1.868912,0.490524,NaN,NaN,NaN,0.000034,...,-0.000886,0.000662,-0.023434,-0.000886,0.293681,37559.738487,5699.304578,392.613020,0.011598,0.0

In [ ]:
my_ta['v_time'].head(200)

0           NaN
1     -0.027829
2      0.073151
3      0.002719
4     -0.271922
5      0.065214
6      0.171653
7      0.332364
8     -0.058985
9     -0.258775
10    -0.335251
11    -0.118688
12    -0.341720
13    -0.051196
14    -0.113356
15    -0.527928
16    -0.564932
17    -0.932257
18    -0.539493
19    -0.031474
20    -0.528140
21     0.045603
22    -0.323354
23    -0.506865
24    -0.677131
25    -1.178835
26    -1.694171
27    -2.244555
28    -1.385841
29    -0.753264
30    -0.726339
31    -0.594980
32    -1.223292
33    -1.255925
34    -1.023135
35    -0.413455
36    -0.728371
37    -0.995626
38    -0.723543
39    -0.899723
40    -0.931646
41    -1.184370
42    -0.595874
43    -0.746109
44    -0.759179
45    -0.667764
46    -0.654280
47    -0.278476
48    -0.376553
49    -0.510192
50    -0.586820
51    -0.801136
52    -0.427042
53    -0.492539
54    -0.699776
55    -0.632633
56    -0.955788
57    -0.947302
58    -0.722567
59    -0.754609
60    -1.021487
61    -0.983827
62    -0.689304
63    -0.541590
64    -0.153932
65    -0.458023
66    -0.237302
67    -0.225820
68    -0.572691
69    -0.261350
70    -0.660255
71    -0.618731
72    -0.435158
73    -0.638108
74    -0.839200
75    -0.709012
76    -0.696014
77    -1.029125
78    -0.266633
79    -0.644658
80    -0.813783
81    -0.879391
82    -0.495707
83    -1.145751
84    -1.535620
85    -1.760988
86    -2.085288
87    -1.041199
88    -0.743254
89    -0.862697
90    -0.327406
91    -0.691281
92    -0.922613
93    -0.463365
94    -0.683921
95    -0.837461
96    -1.644475
97    -1.164137
98    -1.051856
99    -1.223016
100   -1.299131
101   -1.375549
102   -0.681715
103   -0.516629
104   -0.391589
105   -0.450628
106    0.079637
107   -0.178625
108   -0.164274
109    0.021788
110    0.009702
111   -0.218652
112   -0.555049
113   -0.752515
114   -0.393677
115   -0.165733
116   -0.214125
117   -0.706071
118   -0.157251
119   -0.471760
120   -0.661856
121   -0.263084
122   -0.527382
123   -0.566888
124   -0.826636
125   -0.280872
126   -0.529778
127   -0.108876
128    0.128678
129    0.113579
130    0.102764
131    0.295336
132    0.061489
133   -0.014696
134   -0.063880
135   -0.152237
136   -0.099025
137   -0.393229
138   -0.318586
139   -0.306847
140   -0.178605
141   -1.104959
142   -0.753277
143   -0.679487
144   -0.836203
145   -0.828962
146   -0.953372
147   -0.662909
148   -0.376291
149   -0.840620
150   -0.099452
151   -0.717966
152   -1.275838
153   -5.636821
154   -1.637865
155   -1.266068
156   -1.253159
157   -1.131881
158   -1.313823
159   -1.611712
160   -1.594807
161   -1.581838
162   -0.964491
163   -1.176357
164   -1.257112
165   -0.955577
166   -0.535038
167   -0.622184
168   -0.342439
169   -0.474877
170   -0.480668
171   -0.272894
172   -0.331637
173   -0.729054
174   -1.115731
175   -1.012294
176   -0.917067
177   -0.613082
178   -0.462544
179   -0.533147
180   -0.852966
181   -0.736078
182   -0.812653
183   -0.754051
184   -0.723386
185   -1.310663
186   -1.133649
187   -1.447229
188   -1.821519
189   -2.186803
190   -2.312605
191   -4.173219
192   -0.423030
193   -0.203626
194   -0.257691
195   -0.441954
196   -0.260977
197   -2.479157
198   -0.171078
199   -0.048685
Name: v_time, dtype: float64

In [ ]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
v = pd.Series(get_v(bars, bases=['tick'])['tick']).replace([np.inf, -np.inf], np.nan).dropna().to_numpy(dtype=np.float64).reshape(-1,1)
print(v.min())
print(v.max())
ssmean = v.flatten().mean()
ssstd = v.flatten().std()
print(ssmean,'\n', ssstd)
nnew = sc.fit_transform(v)
print(nnew.ravel().mean())
print(nnew.ravel().std())


# nnew

-0.030144272828268273
0.026262114926009494
4.5950169651348896e-07
 0.0010675300677818525
0.5344205422492891
0.018925694593887425

In [ ]:
v

array([[-1.17429848],
       [-1.2373908 ],
       [-2.12423868],
       ...,
       [-1.16817511],
       [-2.18324773],
       [-0.68950309]])

In [ ]:
# bars.reset_index(inplace=True)
my_bars_ta = add_my_features(bars)
# my_bars_ej_ta = add_my_features(bars_ej)
# my_bars_eu_ta = add_my_features(bars_eu)

# my_tas = pd.concat([my_bars_ta, my_bars_ej_ta, my_bars_eu_ta], axis=1)
my_bars_ta

/tmp/ipykernel_3496/2079963133.py:165: RuntimeWarning: invalid value encountered in true_divide
  np.multiply(data, (alpha * scaling_factors[-2]) / scaling_factors[:-1],
/tmp/ipykernel_3496/2079963133.py:170: RuntimeWarning: invalid value encountered in true_divide
  out /= scaling_factors[-2::-1]

,a_tick,a_time,a_volume,v_tick,v_time,v_volume,slopes_tick,slopes_time,slopes_volume,slope_changestick,...,sf_tick,sf_time,sf_volume,gapatr_0,rvol_tick,rvol_time,rvol_volume,downtotal_0,trangeatr_0,topsbuttoms_0
0,-1.183406e-03,NaN,-1.083069e-04,2.232725e-05,NaN,2.043380e-06,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,-1.459341e-07,NaN,-1.062792e-09,-9.164729e-05,-0.002760,-7.759815e-06,-0.000091,-0.002745,-7.717482e-06,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2,3.232457e-08,-1.016003e-04,1.799437e-10,-6.252285e-05,-0.004142,-6.097314e-06,-0.000060,-0.003978,-5.856424e-06,0.000031,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
3,-4.510303e-08,-4.777401e-04,-5.419251e-10,-1.061826e-04,-0.009378,-1.111066e-05,-0.000105,-0.009277,-1.099036e-05,-0.000045,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
4,1.138133e-07,9.224356e-04,1.273864e-09,6.378815e-06,0.000584,6.815003e-07,0.000005,0.000429,5.007064e-07,0.000110,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86233,4.046975e-08,2.999194e-07,1.246502e-08,-1.754746e-06,-0.000042,-1.011792e-06,0.000006,0.000137,3.322427e-06,0.000073,...,7.738814e-09,5.735197e-08,2.383618e-09,0.000787,2.588320e-09,1.455287e-06,8.605424e-10,0.45,-0.999101,0.0
86234,-1.342328e-07,-5.496878e-04,-3.791418e-08,-1.218931e-04,-0.007765,-6.482136e-05,-0.000119,-0.007549,-6.302286e-05,-0.000124,...,-1.644923e-06,-6.736013e-03,-4.646099e-07,0.000326,1.249144e-05,5.068807e-02,3.532565e-06,0.45,-0.989045,1.0
86235,1.719182e-07,2.526264e-05,5.088161e-08,3.781890e-05,0.000113,2.086328e-05,0.000016,0.000048,8.906500e-06,0.000135,...,-6.790222e-07,-9.977936e-05,-2.009662e-07,-0.002172,1.202678e-06,1.067512e-05,3.660130e-07,0.40,-1.001153,-1.0
86236,-4.486741e-08,-4.846105e-06,-1.231094e-08,2.648806e-07,0.000011,1.316538e-07,0.000011,0.000456,5.713319e-06,-0.000005,...,1.118485e-09,1.208070e-07,3.068955e-10,0.001014,5.900777e-11,9.302911e-08,1.457726e-11,0.35,-0.999763,0.0
86237,-6.262702e-09,-8.920823e-06,-1.925523e-09,-5.597009e-06,-0.000211,-3.110926e-06,-0.000002,-0.000088,-1.296822e-06,-0.000014,...,-3.688862e-09,-5.254551e-06,-1.134173e-09,0.000330,2.634794e-08,3.744079e-05,8.139809e-09,0.40,-0.999613,0.0

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit_transform(my_bars_ta)
my_bars_ta*1e6

/home/vahid/miniconda3/lib/python3.8/site-packages/sklearn/utils/extmath.py:847: RuntimeWarning: invalid value encountered in true_divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
/home/vahid/miniconda3/lib/python3.8/site-packages/sklearn/utils/extmath.py:689: RuntimeWarning: Degrees of freedom <= 0 for slice.
  result = op(x, *args, **kwargs)

,a_tick,a_time,a_volume,v_tick,v_time,v_volume,slopes_tick,slopes_time,slopes_volume,slope_changestick,...,sf_tick,sf_time,sf_volume,gapatr_0,rvol_tick,rvol_time,rvol_volume,downtotal_0,trangeatr_0,topsbuttoms_0
0,-1183.405530,NaN,-108.306938,22.327249,NaN,2.043380,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,-0.145934,NaN,-0.001063,-91.647285,-2760.375226,-7.759815,-91.147317,-2745.316421,-7.717482,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2,0.032325,-101.600267,0.000180,-62.522851,-4142.138862,-6.097314,-60.052724,-3978.492972,-5.856424,31.094593,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
3,-0.045103,-477.740080,-0.000542,-106.182588,-9378.170144,-11.110663,-105.032839,-9276.622966,-10.990356,-44.980114,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1000000.0
4,0.113813,922.435578,0.001274,6.378815,584.134094,0.681500,4.686592,429.170305,0.500706,109.719430,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86233,0.040470,0.299919,0.012465,-1.754746,-41.608268,-1.011792,5.762066,136.629216,3.322427,72.909842,...,0.007739,0.057352,0.002384,786.507926,0.002588,1.455287,0.000861,450000.0,-9.991011e+05,0.0
86234,-0.134233,-549.687811,-0.037914,-121.893122,-7764.722016,-64.821357,-118.511139,-7549.286099,-63.022858,-124.273206,...,-1.644923,-6736.012730,-0.464610,326.399337,12.491436,50688.073621,3.532565,450000.0,-9.890452e+05,1000000.0
86235,0.171918,25.262636,0.050882,37.818904,112.673214,20.863279,16.144828,48.100012,8.906500,134.655968,...,-0.679022,-99.779364,-0.200966,-2171.825864,1.202678,10.675121,0.366013,400000.0,-1.001153e+06,-1000000.0
86236,-0.044867,-4.846105,-0.012311,0.264881,10.517317,0.131654,11.494897,456.415011,5.713319,-4.649932,...,0.001118,0.120807,0.000307,1014.051598,0.000059,0.093029,0.000015,350000.0,-9.997632e+05,0.0
86237,-0.006263,-8.920823,-0.001926,-5.597009,-210.986717,-3.110926,-2.333172,-87.952037,-1.296822,-13.828069,...,-0.003689,-5.254551,-0.001134,329.577352,0.026348,37.440786,0.008140,400000.0,-9.996125e+05,0.0

## Calculating Entropy Features and add tick_rule

In [ ]:
bars.rename(columns={'tick_num':'end_index'}, inplace=True)
bars['start_index'] = bars['end_index'].shift(1)
bars.loc[0,'start_index'] = 0
bars['start_index'] = bars['start_index'].astype(int)
# bars.reset_index(inplace=True)
# bars = bars[['date_time', 'open', 'high', 'low', 'close', 'volume', 'cum_dollar_value' 'start_index', 'end_index']]
bars.head()

,index,date_time,end_index,open,high,low,close,volume,cum_buy_volume,cum_ticks,cum_dollar_value,start_index
0,0,2010-01-08 15:28:10.393999872,103428636,20.649003,20.579068,20.620443,20.549609,1797.550603,1978.0,735,460023.4525,0
1,1,2010-01-08 15:36:47.540000000,103429274,20.547324,20.554540,20.525300,20.489798,1793.052819,2007.0,638,459443.5000,103428636
2,2,2010-01-08 15:43:02.888000000,103429828,20.485431,20.440145,20.467368,20.459934,1798.951843,1796.0,554,459362.0100,103429274
3,3,2010-01-08 15:49:34.744000000,103430410,20.459050,20.435964,20.397313,20.436435,1799.468348,1693.0,582,459108.9450,103429828
4,4,2010-01-08 16:07:10.780000000,103431693,20.457700,20.485663,20.438611,20.414820,1797.285147,2257.0,769,459184.4575,103430410

In [ ]:
%%time
%autoreload 2
entropy_feat = mylib.feature_generation.get_entropy_features(tick_df, bars, verbose=True, n_jobs=n_cpus)
entropy_feat.tail()

Calculating shannon entropy...
24 jobs used for multiprocessing...
2021-08-29 08:26:22 100.0% _calc_entropy done after 1.05 minutes. Remaining 0.0 minutes..

Calculating lempel_ziv entropy...
24 jobs used for multiprocessing...
2021-08-29 08:27:41 100.0% _calc_entropy done after 1.25 minutes. Remaining 0.0 minutes..

Calculating plug_in entropy...
24 jobs used for multiprocessing...
2021-08-29 08:29:04 100.0% _calc_entropy done after 1.3 minutes. Remaining 0.0 minutes.s.

Calculating konto entropy...
24 jobs used for multiprocessing...
2021-08-29 08:31:44 100.0% _calc_entropy done after 2.61 minutes. Remaining 0.0 minutes..

CPU times: user 42.9 s, sys: 34.5 s, total: 1min 17s
Wall time: 6min 29s

       shannon_entropy  lempel_ziv_entropy  plug_in_entropy  konto_entropy
24430         0.998068            0.138224         0.998038       0.908309
24431         0.998110            0.138834         0.998138       0.887861
24432         0.998315            0.143120         0.998346       0.881762
24433         0.997629            0.138969         0.997661       0.899762
24434         0.999575            0.139263         0.999591       0.898169

In [ ]:
%%time
%autoreload 2
trade_micro_feat = mylib.feature_generation.get_trade_micro_features(tick_df,
                                                                     bars,
                                                                     verbose=True,
                                                                     n_jobs=n_cpus)
trade_micro_feat.tail()

Calculating kyle lambda...
24 jobs used for multiprocessing...
2021-08-29 08:22:58 100.0% _calc_lambda done after 1.0 minutes. Remaining 0.0 minutes.s.

Calculating amihud lambda...
24 jobs used for multiprocessing...
2021-08-29 08:24:06 100.0% _calc_lambda done after 1.07 minutes. Remaining 0.0 minutes..

Calculating hasbrouck lambda...
24 jobs used for multiprocessing...
2021-08-29 08:25:15 100.0% _calc_lambda done after 1.1 minutes. Remaining 0.0 minutes.s.

CPU times: user 33.8 s, sys: 22.8 s, total: 56.6 s
Wall time: 3min 21s

,kyle_coef,kyle_tvalue,amihud_coef,amihud_tvalue,hasbrouck_coef,hasbrouck_tvalue
24430,-25193.286096,-1.080616,9.941739,1.099945,-151.924054,-1.114511
24431,-12401.390498,-0.525001,4.975442,0.543668,-107.503458,-0.777829
24432,9724.788299,0.444693,3.680980,0.434339,107.358201,0.721318
24433,-10360.764431,-0.469443,4.194564,0.489684,-107.433812,-0.762538
24434,10433.431544,0.465754,3.955273,0.455438,107.438459,0.730441

In [ ]:
other_micro_features = mylib.feature_generation.get_other_features(bars, periods)
other_micro_features.tail()

       role_measure  corwin_schultz  roll_impact  bekker_parkinson      vpin
24430      0.009042        0.000000   693.563692          0.001047  1.621329
24431      0.006574        0.001375   504.238212          0.000000  1.617278
24432      0.005339        0.000000   409.539289          0.001105  1.232670
24433      0.007179        0.000000   550.647310          0.001004  1.462598
24434      0.005785        0.000000   443.744815          0.001123  1.406895

In [ ]:
%%time

if 'start_index' in bars.columns:
    bars.drop('start_index', axis=1, inplace=True)
if 'end_index' in bars.columns:
    bars.drop('end_index', axis=1, inplace=True)
if 'cum_ticks' in bars.columns:
    bars.drop('cum_ticks', axis=1, inplace=True)
if 'cum_dollar_value' in bars.columns:
    bars.drop('cum_dollar_value', axis=1, inplace=True)
if 'cum_buy_volume' in bars.columns:
    bars.drop('cum_buy_volume', axis=1, inplace=True)

CPU times: user 12.9 ms, sys: 3.93 ms, total: 16.8 ms
Wall time: 16.1 ms

In [ ]:
df_list = [bars, entropy_feat, trade_micro_feat, other_micro_features, ta_features, ts_features]
f_df = pd.concat(df_list, axis=1)
# f_df = f_df.loc[:,~f_df.columns.duplicated()]

In [ ]:
del bars, ta_features, ts_features, entropy_feat, trade_micro_feat, other_micro_features, tick_df

## Dropping duplicate columns, and columns with lots of zeros and nulls

In [ ]:
# %autoreload 2
# prev_shape = f_df.shape

# f_df = mylib.feature_selection.drop_null_columns(f_df)
# f_df = mylib.feature_selection.drop_zeros(f_df)

# duplicated_feat, duplicated_feat_pairs = mylib.feature_selection.find_duplicate_feat(f_df)
# f_df = f_df[duplicated_feat_pairs.keys()]
# f_df = mylib.feature_selection.drop_duplicate_columns(f_df)

# print('Number of droped duplicate features: '+str(len(duplicated_feat)))
# print(f'features_df previous shape is {prev_shape} and curent shape is {f_df.shape}')

In [ ]:
# nulls = mylib.feature_selection.find_null_columns(f_df)
# zeros = mylib.feature_selection.find_zeros(f_df)

# nulls, zeros

In [ ]:
%%time
%autoreload 2

duplicate_names = f_df.columns[f_df.columns.duplicated()].to_list()
# duplicate_values = mylib.feature_selection.find_duplicate_columns(f_df)
# nulls = mylib.feature_selection.find_null_columns_np(f_df)
# zeros = mylib.feature_selection.find_zeros_np(f_df)

drops = duplicate_names + duplicate_values
drops = list(set(drops))
# print(f'Useless columns: {drops}')
print('Number of usless columns: '+str(len(drops)))
# print(f'features_df previous shape is {prev_shape} and curent shape is {f_df.shape}')

In [ ]:
f_df.drop(drops, axis=1, inplace=True)

In [ ]:
f_df = f_df.loc[:, ~f_df.columns.duplicated()]

In [ ]:
# col_list = list(f_df.columns)
# import pickle
# pk_path = Path().resolve().parent/'data'/'features_data'/'feature_names.pkl'
# with open(pk_path, 'wb') as file:
#     pickle.dump(col_list, file)

In [ ]:
# f_df_file_path = Path().resolve().parent/'data'/'features_data'/'USDJPY_db_459K_f_df.h5'
# f_df.to_hdf(f_df_file_path, mode='w', key='s', data_columns=True)

labels_path = Path().resolve().parent/'data'/'features_data'/'USDJPY_50bpd_labels.h5'
labels.to_hdf(labels_path, mode='w', key='s', data_columns=True)

events_path = Path().resolve().parent/'data'/'features_data'/'USDJPY_50bpd_events.h5'
triple_barrier_events.to_hdf(events_path, mode='w', key='s', data_columns=True)

## *** End***

# Mutual Information Analysis

In [ ]:
# # to obtain the mutual information values
# from sklearn.feature_selection import mutual_info_classif, mutual_info_regression

# # to select the features
# from sklearn.feature_selection import SelectKBest, SelectPercentile

# # calculate the mutual information between the variables and the target
# # the smaller the value of the mi, the less information we can infer from
# # the feature about the target

# mi = mutual_info_classif(X_train, y_train)
# # 1) let's capture the above array in a pandas series
# # 2) add the variable names in the index
# # 3) sort the features based on their mutual information value
# # 4) and make a var plot

# mi = pd.Series(mi)
# mi.index = X_train.columns
# mi = mi.sort_values(ascending=False)
# mi.head()
# ax = plt.gca()
# ax.tick_params(color='w', which='both')

# ax.set_xlabel('Features', color='w')
# ax.set_ylabel('Mutual Information', color='w')
# ax.tick_params(which='both', color='w', labelcolor='w')
# mi.sort_values(ascending=False).plot.bar(figsize=(20, 6))
# plt.show()

# Chi2 Analysis

In [ ]:
# # the scaler - for min-max scaling
# from sklearn.preprocessing import MinMaxScaler
# # set up the scaler
# scaler = MinMaxScaler()

# # fit the scaler to the train set, it will learn the parameters
# scaler.fit(X_train)

# # transform train and test sets
# X_train_scaled = scaler.transform(X_train)
# X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train.columns)

# # to determine the chi2 value
# from sklearn.feature_selection import chi2
# # calculate the chi2 p_value between each of the variables
# # and the target

# # chi2 returns 2 arrays, one contains the F-Scores which are then
# # evaluated against the chi2 distribution to obtain the pvalue.
# # The pvalues are in the second array
# f_score = chi2(X_train_scaled, y_train)

# pvalues = pd.Series(f_score[1])
# pvalues.index = X_train.columns
# pvalues = pvalues.sort_values(ascending=True)
# pvalues.head()
# # pvalues.sort_values(ascending=True).plot.bar(figsize=(20, 6))
# # plt.ylabel('CHI2')

In [ ]:
import pandas_ta as ta
bars.ta.indicator_list()

NameError: name 'bars' is not defined

# PCA

In [ ]:
# from sklearn.decomposition import PCA
# # X_train, X_test, y_train, y_test = train_test_split_scale(X, y, 0.2, True)
# pca = PCA(n_components=10)
# # prepare transform on dataset
# pca.fit(X_train)

# # apply transform to dataset
# X_train_reduced = pca.transform(X_train)
# X_train_reduced[0]

In [ ]:
# Xdot = pd.DataFrame(get_orthogonal_features(X.iloc[:,:20]), index=X.index).add_prefix("PCA_")
# Xdot.head()

# KMeans Clustering

In [ ]:
# from sklearn.cluster import KMeans
# kmeans = KMeans(n_clusters=3)
# identified_clusters = kmeans.fit_predict(X_train_scaled.T)
# # print(identified_clusters.shape)
# data_with_clusters = X_train_scaled.copy().T
# data_with_clusters['Kmeans_Cluster'] = identified_clusters
# # print(data_with_clusters.shape)
# plt.figure(figsize=(14,8))
# # sns.scatterplot(x=data_with_clusters[0],y=data_with_clusters[938],hue=data_with_clusters['Kmeans_Cluster'],
# #                 c=data_with_clusters['Kmeans_Cluster'], palette=['g', 'r','c','m', 'b', 'y', 'k'])
# sns.scatterplot(x=data_with_clusters[0],y=data_with_clusters[938],hue=data_with_clusters['Kmeans_Cluster'],
#                 c=data_with_clusters['Kmeans_Cluster'], palette="deep")
# # plt.legend()
# # plt.xlim(-1,1)
# # plt.ylim(-90,90)
# plt.show()

In [ ]:
# data_with_clusters['Kmeans_Cluster'].value_counts()
# first_feat = data_with_clusters[data_with_clusters['Kmeans_Cluster']==0].index
# list(first_feat)

## Selecting the number of clusters for KMeans (The Elbow Method)

In [ ]:
# wcss=[]

# for i in range(1,24):
#     kmeans = KMeans(i)
#     kmeans.fit(X_train_scaled.T)
#     wcss_iter = kmeans.inertia_
#     wcss.append(wcss_iter)
    
# number_clusters = range(1,24)
# plt.figure(figsize=(12,8))

# plt.plot(number_clusters,wcss)
# plt.title('The Elbow Method')
# plt.xlabel('Number of clusters')
# plt.ylabel('Within-cluster Sum of Squares')
# plt.xlim(0,10)
# plt.show()

# Plot Random Forest Feature Importance (Soledad Ghali)

In [ ]:
# from sklearn.ensemble import RandomForestClassifier

# # first_group_feat = data_with_clusters[data_with_clusters['Kmeans_Cluster']==0].index
# # list(first_feat)
# corr_groups = calc_corr_matrix(X_train)

# # add all features of the group to a list
# features = list(corr_groups[0].feature2)+[corr_groups[0].feature1.iloc[0]]
# # features = X_train.columns

# # train a random forest 
# rf = RandomForestClassifier(n_estimators=200, random_state=39, max_depth=4)
# rf.fit(X_train_scaled[features].fillna(0), y_train)
# get the feature importance attributed by the 
# random forest model (more on this in coming lectures)

# feat_importance = pd.concat(
#     [pd.Series(features),
#      pd.Series(rf.feature_importances_)], axis=1)

# feat_importance.columns = ['feature', 'importance']

# # sort features by importance, most important first
# feat_importance = feat_importance.sort_values(by='importance', ascending=False)
# feat_importance

In [ ]:
# Plot feature importance

# plt.figure(figsize=(18,8))
# ax = plt.gca()
# ax.set_xlabel('Features', color='w')
# ax.set_ylabel('Importance', color='w')
# ax.tick_params(which='both', color='w', labelcolor='w')
# ax.set_xticklabels(labels=feat_importance['feature'],rotation=90)
# plt.plot(feat_importance['feature'], feat_importance['importance'])
# plt.show()

## Draw Decision Tree

In [ ]:
# plt.figure(figsize=(28,20))
# _ = tree.plot_tree(rf.estimators_[199], feature_names=features, class_names = ['up', 'stay', 'down'], filled=True, fontsize=12)

## Calculate Model Metrics such as confusion_matrix

In [ ]:
# from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# y_pred = rf.predict(X_test_scaled[features])
# accuracy_score(y_test, y_pred)
# confusion_matrix(y_test, y_pred)
# print(classification_report(y_test, y_pred))